### ISSUE TITLE
建议增加功能

### ISSUE THREAD

**Issue by guoqingaa** [wing-kai/epub-manga-creator#1]
能否增加如下功能：
  a. 图片压缩优化、去色灰度图支持（Kindle，ireader 等水墨屏支持）
  b. 设定某页为封面

**Comment by guoqingaa** [comment]
使用 Electron 打一个离线包！

**Comment by guoqingaa** [comment]
图片支持横屏（旋转），如小人书（连环画）

**Comment by wing-kai** [comment]
1、图片压缩这个我不打算做，我这里只负责打包，不做过多的图片处理。
2、设定封面这个已经有了，鼠标指针悬停在页面的时候，页面底部左侧的书本图标就是设定封面功能

**Comment by lunarjoll** [comment]
请问能支持mobi吗？我这里经过calibre转码后图片变得奇怪。
