### ISSUE TITLE
封面问题

### ISSUE THREAD

**Issue by unicorn0225** [wing-kai/epub-manga-creator#10]
首先这是一个很好的一个项目。是否能添加设置是否把第一张图片设置为封面，选否的话第一张图片就是封面，第二张才是page1，我的资源就是有cover图片，把它删了也可以，但是加个选项我觉得会更好。
tip：个人能力有限，不能pull request，也不知道具体难度，只能在这提提意见了，希望作者不要怪罪，感谢🙏

**Comment by wing-kai** [comment]
目前第一张图片默认就是封面

**Comment by wing-kai** [comment]
> 是的，但是现在第一张图片也是page1， 可不可以设置第一张图片只是用来设置封面，名字是page.png,第二张才是page1.png。我的资源有一张单独的封面，而不是用漫画的第一页设置为封面。

我懂你意思了，可以这么干，我到时候抽空更新一下

**Comment by wing-kai** [comment]
目前已加入这个功能，在页面里设置 cover -> alone 即可
