### ISSUE TITLE
翻页阅读的一点改进

### ISSUE THREAD

**Issue by unicorn0225** [wing-kai/epub-manga-creator#11]
翻页模式阅读双页漫画中间会有一条阴影线，iBook购买的就没有，可能是CSS设置的问题，我也不清楚，具体可以看图片
链接：https://wwe.lanzoui.com/ihFKHsnchte
自购的epub文件：https://wwe.lanzoui.com/itxxZsnchrc
用本仓库制作的文件：https://wwe.lanzoui.com/iGD90snchni
这个其实不算什么问题，但是个人有点强迫症，用了很多的软件，都有这个问题。

**Comment by wing-kai** [comment]
不同大小的窗口，有时候会显示这条黑线。
我在iBooks用试读模式看，也会看到这条「线」，但调整一下窗口大小之后又好了。

**Comment by wing-kai** [comment]
我尝试修复了这个问题，你那边方便再测试一下看看？

**Comment by fan-cy** [comment]
> 翻页模式阅读双页漫画中间会有一条阴影线，iBook购买的就没有，可能是CSS设置的问题，我也不清楚，具体可以看图片 链接：https://wwe.lanzoui.com/ihFKHsnchte 自购的epub文件：https://wwe.lanzoui.com/itxxZsnchrc 用本仓库制作的文件：https://wwe.lanzoui.com/iGD90snchni 这个其实不算什么问题，但是个人有点强迫症，用了很多的软件，都有这个问题。


你好我现在也遇到这个问题，我提了一个[新issue](https://github.com/wing-kai/epub-manga-creator/issues/13)
我发现不只是中间，其实右边也会有竖线， 中间的竖线是左边的图的，右边的竖线是右边的图的。
我试了很多preserveAspectRatio参数组合都没有解决。有时候在ipad上显示，有时候不显示但是翻页时候又显示，然后在macbook上显示，在imac上又不显示什么的。
但是看了在ibooks买的，就无论什么设备怎么缩放都没有问题。
由于我没找到成功破解ibooks epub的方法，看不到ibooks的xhtml页面是怎么写的。

我看到你之前有分享过购买的ibooks epub文件，能麻烦你再分享一下吗？谢谢🙏

**Comment by wing-kai** [comment]
@fan-cy 
那个文件现在已经没了……
