### ISSUE TITLE
转换的 EPUB 漫画只有封面大小可以自适配，其余页面图片很小

### ISSUE THREAD

**Issue by JokerM7776** [wing-kai/epub-manga-creator#12]
设定了页面尺寸，拉抻方式后下载的 EPUB 打开只有第一页（封面）的尺寸正确，其他页面的图片都极小

转换内容：含 WEBP 图片的 ZIP
图片数量：32

**Comment by wing-kai** [comment]
不太理解问题

**Comment by JokerM7776** [comment]
由于时间久远及没有测试设备，issue 先关闭。之后有空再使用的时候反馈。
