### ISSUE TITLE
preserveAspectRatio参数问题

### ISSUE THREAD

**Issue by fan-cy** [wing-kai/epub-manga-creator#13]
最近想把手里的图打包成epub，找来找去觉得这个webUI很好用。
但是遇到了一点问题，有的图（似乎原因是宽度奇数），在对开页，ipad竖屏观看的情况下，左右2页中间会有一条白色竖线。
查阅了一下资料，应该是preserveAspectRatio参数设置问题。
webUI的缩放选项三种都有，但是对齐选项只有 center（xMidYMid） 和 between（左xMinYMid+右xMaxYMid）两个选项。
可否考虑增加【左xMaxYMid+右xMinYMid】这样的选项，这样从中间对齐应该可以消除中间竖线问题。
个人完全不懂技术，只是这几天查阅资料分析的原因，如有错误请见谅，希望作者能看到，真的很喜欢这个webUI。

**Comment by fan-cy** [comment]
我试了手动调整进行x方向中间对齐还是不行，center和between也是，中间的线可能不显示，但是在翻页的时候会出现。
另外我用macbook（macos12）全屏时能看到中间和右侧有两条竖线，试过  对齐center/between/middle和 缩放none/slice/meet 各种组合还是不行，直接把preserveAspectRatio属性去掉也不行。看来不是preserveAspectRatio的问题？
由于我遇到问题的图片分辨率是1359*1920，我试着用这个分辨率的纯色图试了一下可以复现。
我看了一下xhtml文件和opf文件对viewport/viewbox/img 的尺寸定义，感觉可能是这里出问题在某些分辨率或者宽高比下会产生缩放问题产生白边。

page xhtml：
<head>
<meta name="viewport" content="width=1359, height=1920"/>
</head>
<body><div class="main">
<svg  width="100%" height="100%" viewBox="0 0 1359 1920">
<image width="100%" height="100%" preserveAspectRatio="xMaxYMid slice" xlink:href="../image/i_0000.jpeg" />
</svg></div></body>

opf：
<meta property="fixed-layout-jp:viewport">width=1359, height=1920</meta>

![截屏2022-05-17 23.29.51.png](https://s2.loli.net/2022/05/17/nZhBkoQlcE3FCP4.png)

**Comment by wing-kai** [comment]
macOS Ventura 下的Apple book好像自动解决了这个问题……
我是按照你的分辨率创建了相关的纯色图片做的测试。

其实很久以前我也遇到过类似的问题，但我也没有太好的解决方案，感觉更多是阅读器本身的问题……
