### ISSUE TITLE
文件打包规范

### ISSUE THREAD

**Issue by fan-cy** [wing-kai/epub-manga-creator#14]
epub规范规定mimetype文件必须在文件头。我用zipinfo查看webUI打包的epub发现mimetype并不在文件头。

4.2.3 OCF ZIP container media type identification
EPUB creators MUST include the mimetype file as the first file in the [OCF ZIP container](https://www.w3.org/TR/epub-33/#dfn-ocf-zip-container). In addition:

The contents of the mimetype file MUST be the MIME media type [[rfc2046](https://www.w3.org/TR/epub-33/#bib-rfc2046)] string application/epub+zip encoded in US-ASCII [[us-ascii](https://www.w3.org/TR/epub-33/#bib-us-ascii)].
The mimetype file MUST NOT contain any leading or trailing padding or white space.
The mimetype file MUST NOT begin with the Unicode byte order mark U+FEFF.
EPUB creators MUST NOT compress or encrypt the mimetype file.
EPUB creators MUST NOT include an extra field in its ZIP header.

**Comment by fan-cy** [comment]
之前只发现mimetype问题，刚又用epubcheck检查了一下opf文件中还有以下报错

1. meta信息不能少于1
2. uuid无效，猜测是参数uuid值中写入了【urn:uuid:】文字？
3. 修改时间语法错误，CCYY-MM-DDThh:mm:ssZ

![Xnip2022-05-17_11-38-36.jpg](https://s2.loli.net/2022/05/17/JLTkiqRxV9B4tAr.jpg)

**Comment by fan-cy** [comment]
另外我查看压缩包信息，发现webUI打包的全部文件都不压缩仅存储，
用sigil和calibre等工具打包时是mimetype文件仅存储，其余文件压缩。
然后我看了一下我在ibooks买的书就离谱，根本没打包成zip，直接就是文件夹加了个.epub域名而已。
epub规范什么的好像没什么卵用，也就是符合规范能提高兼容性？

**Comment by wing-kai** [comment]
> epub规范什么的好像没什么卵用，也就是符合规范能提高兼容性？

我猜应该是的😅
