### ISSUE TITLE
使用自建pages，页面显示空白

### ISSUE THREAD

**Issue by dyxang** [wing-kai/epub-manga-creator#2]
因为是github在我这儿打开的比较慢，所以就clone到码云上去了，结果打开空白，请问是什么原因呢？
我的：[http://dyxang.gitee.io/pic2epub/](url)
console
`(index):13 GET http://dyxang.gitee.io/pic2epub/dist/assets.js?v=1552210108194 404 (Not Found)
(index):52 Uncaught TypeError: Cannot read property 'commons' of undefined
    at (index):52
    at (index):54
​`

**Comment by wing-kai** [comment]
不了解，但你现在可以再试试
