### ISSUE TITLE
可否将此网站部署于本地？

### ISSUE THREAD

**Issue by Lucerne-Grey** [wing-kai/epub-manga-creator#21]
感谢分享，对于此类优秀的软件，我总有一些收集的欲望，生怕某天404。所以，在不影响作者利益的情况下，可否将该网站部署于本地？
磕头了

**Comment by wing-kai** [comment]
都一个开源软件了，哪来什么不给部署在本地的规定，本地随便玩又不会怎样。
另外，就这点事情别磕头。
