### ISSUE TITLE
Support for webp

### ISSUE THREAD

**Issue by Youxikong** [wing-kai/epub-manga-creator#3]
希望可以支持webp。是漫画标准不支持webp吗？

**Comment by wing-kai** [comment]
支不支持其实是阅读器的问题。

**Comment by Youxikong** [comment]
我是指不能添加webp的这个问题。

**Comment by wing-kai** [comment]
即将更新

**Comment by jilulu** [comment]
今天在转换epub的时候也考虑了一下图片存储效率的问题。查阅了一下epub标准 [http://idpf.org/epub/20/spec/OPS_2.0.1_draft.htm#Section2.3.4](http://idpf.org/epub/20/spec/OPS_2.0.1_draft.htm#Section2.3.4)

> The inline element img should only be used to refer to images with OPS Core Media Types of GIF (http://www.w3.org/Graphics/GIF/spec-gif89a.txt), PNG (RFC 2083), JPG/JFIF (http://www.w3.org/Graphics/JPEG) or SVG (http://www.w3.org/TR/SVG11/). The required URI attribute, src, is used to reference the image resource, which must be listed in the Manifest.

如果理解没错的话，img标签只应该引用gif, png, jpg 和 svg格式的图片。所以使用webp格式图片貌似并不被认可。

不过我并没有实际测试过实机表现，如果在这方面有踩过坑的话还请不吝赐教。

顺带一提，现在负责任的扫图组应该都是会用灰阶色彩空间来发布扫图资源的。在减小文件体积时，不妨看一下您的漫画扫图文件的色彩空间，如果是RGB的话不妨转为grayscale，可以提升不少储存效率。

**Comment by Youxikong** [comment]
> 今天在转换epub的时候也考虑了一下图片存储效率的问题。查阅了一下epub标准 http://idpf.org/epub/20/spec/OPS_2.0.1_draft.htm#Section2.3.4
> 
> > The inline element img should only be used to refer to images with OPS Core Media Types of GIF (http://www.w3.org/Graphics/GIF/spec-gif89a.txt), PNG (RFC 2083), JPG/JFIF (http://www.w3.org/Graphics/JPEG) or SVG (http://www.w3.org/TR/SVG11/). The required URI attribute, src, is used to reference the image resource, which must be listed in the Manifest.
> 
> 如果理解没错的话，img标签只应该引用gif, png, jpg 和 svg格式的图片。所以使用webp格式图片貌似并不被认可。
> 
> 不过我并没有实际测试过实机表现，如果在这方面有踩过坑的话还请不吝赐教。
> 
> 顺带一提，现在负责任的扫图组应该都是会用灰阶色彩空间来发布扫图资源的。在减小文件体积时，不妨看一下您的漫画扫图文件的色彩空间，如果是RGB的话不妨转为grayscale，可以提升不少储存效率。

了解，谢谢你的指点。

**Comment by wing-kai** [comment]
现在支持了，不过我个人并不用webp格式
