### ISSUE TITLE
建议增加一个保存配置与导入配置的功能

### ISSUE THREAD

**Issue by genox-wang** [wing-kai/epub-manga-creator#4]
感谢作者的分享，工具用起来很方法，唯一的瑕疵就是在做连载漫画的时候，牵涉到漫画更新的问题，现在做好的epub只有就需要重新做，最麻烦的就是分章节的操作了，重新来一次的话会很崩溃，建议增加一个配置持久化的功能

**Comment by wing-kai** [comment]
即将更新

**Comment by wing-kai** [comment]
加上了✅
